package ssuPlector.domain.category;

public enum Part {
    FRONTEND,
    BACKEND,
    FULLSTACK,
    PM,
    PO,
    BUSINESS_ANALYST,
    SYSTEMS_ANALYST,
    SOFTWARE_ARCHITECT,
    QUALITY_ASSURANCE_ENGINEER,
    DEVOPS_ENGINEER,
    TECHNICAL_WRITER,
    DATABASE_ADMINISTRATOR,
    NETWORK_ENGINEER,
    SECURITY_ANALYST
}
